const genders = [
  { id: 0, value: "Unisex" },
  { id: 1, value: "Male" },
  { id: 2, value: "Female" },
  { id: 3, value: "Agender" },
  { id: 4, value: "Androgyne" },
  { id: 5, value: "Androgynou" },
  { id: 6, value: "Bigender" },
  { id: 7, value: "Cis" },
  { id: 8, value: "Cis Female" },
  { id: 9, value: "Cis Male" },
  { id: 10, value: "Cis Man" },
  { id: 11, value: "Cis Woman" },
  { id: 12, value: "Cisgender" },
  { id: 13, value: "Cisgender Female" },
  { id: 14, value: "Cisgender Male" },
  { id: 15, value: "Cisgender Man" },
  { id: 16, value: "Cisgender Woman" },
  { id: 17, value: "Female to Male" },
  { id: 18, value: "FTM" },
  { id: 19, value: "Gender Fluid" },
  { id: 20, value: "Gender Nonconforming" },
  { id: 21, value: "Gender Questioning" },
  { id: 22, value: "Gender Variant" },
  { id: 23, value: "Genderqueer" },
  { id: 24, value: "Intersex" },
  { id: 25, value: "Male to Female" },
  { id: 26, value: "MTF" },
  { id: 27, value: "Neither" },
  { id: 28, value: "Neutrois" },
  { id: 29, value: "Non-binary" },
  { id: 30, value: "Pangender" },
  { id: 31, value: "Trans" },
  { id: 32, value: "Trans Female" },
  { id: 33, value: "Trans Male" },
  { id: 34, value: "Trans Man" },
  { id: 35, value: "Trans Person" },
];

export default genders;
